# action.yml
name: "Run ROC Sensor Docker Container"
description: "A GitHub Action to run the ROC sensor container with custom configuration and simulate traffic."
inputs:
    patterns_yaml:
        description: "The YAML content for the patterns file (pattern.yaml) as a string. This is required."
        required: true
    docker_image:
        description: "The Docker image to run (e.g., hanshal785/roc:v5)"
        required: true
    server_url:
        description: "The API server URL for ROC"
        required: true
    api_key:
        description: "The API key for ROC"
        required: true
    libssl_host_path:
        description: "Path on the host for libssl.so.3 (default: /lib/x86_64-linux-gnu/libssl.so.3)"
        required: false
        default: "/lib/x86_64-linux-gnu/libssl.so.3"
    libcrypto_host_path:
        description: "Path on the host for libcrypto.so.3 (default: /lib/x86_64-linux-gnu/libcrypto.so.3)"
        required: false
        default: "/lib/x86_64-linux-gnu/libcrypto.so.3"
    container_name:
        description: "Name for the Docker container (default: roc-action-container)"
        required: false
        default: "roc-action-container"
    output_dir_host_path:
        description: "Path on the host to store output files from the container (default: ./roc-action-output)"
        required: false
        default: "./roc-action-output"
    extra_docker_args:
        description: "Extra arguments to pass to the docker run command (optional)"
        required: false
        default: ""
outputs:
    container_name:
        description: "The name of the started container"
runs:
    using: "node20"
    main: "dist/index.js"
branding:
    icon: "play"
    color: "blue"
